using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Borderlands_Save_Editor {
	/// <summary>
	/// Identifies a mission.
	/// </summary>
	public enum MissionID {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
		Base_FreshOffTheBus,
		Base_TheDoctorIsIn,
		Base_SkagsAtTheGate,
		Base_ClaptrapRescue,
		Base_FixerUpper,
		Base_BlindingNineToes,
		Base_NineToesMeetTKBaha,
		Base_NineToesTKsFood,
		Base_GotGrenades,
		Base_NineToesTakeHimDown,
		Base_NineToesTimeToCollect,
		Base_JobHunting,
		Base_TKHasMoreWork,
		Base_WhyAreTheyHere,
		Base_TKsLifeAndLimb,
		Base_ByTheSeedsOfYourPants,
		Base_CatchARide,
		Base_BoneHeadsTheft,
		Base_GetALittleBloodOnTheTires,
		Base_ThePissWashHurdle,
		Base_HiddenJournalTheAridBadlands,
		Base_ClaptrapRescueTheLostCave,
		Base_ShockCrystalHarvest,
		Base_ReturnToZed,
		Base_SledgeMeetShep,
		Base_BrakingWind,
		Base_GetTheFlockOuttaHere,
		Base_SledgeTheMineKey,
		Base_ScavengerSniperRifle,
		Base_TheLegendOfMoeAndMarley,
		Base_CircleOfDeathMeatAndGreet,
		Base_CircleOfDeathRound1,
		Base_CircleOfDeathRound2,
		Base_CircleOfDeathFinalRound,
		Base_SledgeToTheSafeHouse,
		Base_ClaptrapRescueSafeHouse,
		Base_ScavengerCombatRifle,
		Base_WhatHitTheFan,
		Base_SledgeBattleForTheBadlands,
		Base_FindBruceMcClane,
		Base_ProductRecall,
		Base_InsultToInjury,
		Base_ScheminThatSabotage,
		Base_LeavingFyrestore,
		Base_BigGameHunter,
		Base_GettingLucky,
		Base_PoweringTheFastTravelNetwork,
		Base_ScavengerRevolver,
		Base_FuelFeud,
		Base_DeathRacePandora,
		Base_GhostsOfTheVault,
		Base_WellTheresYourProblemRightThere,
		Base_RoadWarriorsHotShots,
		Base_RoadWarriorsBanditApocalypse,
		Base_PowerToThePeople,
		Base_ClaptrapRescueNewHaven,
		Base_KingTossing,
		Base_CorrosiveCrystalHarvest,
		Base_ClaptrapRescueTetanusWarren,
		Base_LikeAMothToFlame,
		Base_IsTKOK,
		Base_SeekOutTannis,
		Base_ScootersUsedCarParts,
		Base_UpToOurEars,
		Base_FirepowerAllSalesAreFinal,
		Base_FirepowerMarketCorrection,
		Base_FirepowerPlightOfTheMiddleMan,
		Base_JacksOtherEye,
		Base_ScavengerSubmachineGun,
		Base_HiddenJournalRustCommonsWest,
		Base_MeetCrazyEarl,
		Base_GetOffMyLawn,
		Base_TodaysLessonHighExplosives,
		Base_ClaptrapRescueScrapyard,
		Base_HairOfTheDog,
		Base_MissingPersons,
		Base_TwoWrongsMakeARight,
		Base_MiddleOfNowhereNoMoreInvestigate,
		Base_MiddleOfNowhereNoMoreFusesReally,
		Base_MiddleOfNowhereNoMoreSmallFavor,
		Base_MiddleOfNowhereNoMoreScootOnBack,
		Base_AltarEgoBurningHeresy,
		Base_ScavengerShotgun,
		Base_HiddenJournalRustCommonsEast,
		Base_CircleOfSlaughterMeatAndGreet,
		Base_CircleOfSlaughterRound1,
		Base_CircleOfSlaughterRound2,
		Base_CircleOfSlaughterFinalRound,
		Base_TheNextPiece,
		Base_EarlNeedsFoodBadly,
		Base_ClaptrapRescueKromsCanyon,
		Base_JaynistownSecretRendezvous,
		Base_RelightTheBeacons,
		Base_ABugProblem,
		Base_AltarEgoTheNewReligion,
		Base_AltarEgoGodlessMonsters,
		Base_SmokeSignalsInvestigateOldHaven,
		Base_SmokeSignalsShutThemDown,
		Base_BanditTreasureThreeCorpsesThreeKeys,
		Base_BanditTreasureXMarksTheSpot,
		Base_GreenThumb,
		Base_JaynistownABrothersLove,
		Base_DumpsterDivingForGreatJustice,
		Base_JaynistownSpreadTheWord,
		Base_JaynistownGettingWhatsComingToYou,
		Base_WantedFreshFish,
		Base_IvegotASinkingFeeling,
		Base_JaynistownUnintendedConsequences,
		Base_JaynistownCleaningUpYourMess,
		Base_ClaptrapRescueTrashCoast,
		Base_BaitAndSwitch,
		Base_EarlsBestFriend,
		Base_HouseHunting,
		Base_AnotherPieceOfThePuzzle,
		Base_NotWithoutMyClaptrap,
		Base_ClaptrapRescueOldHaven,
		Base_TheFinalPiece,
		Base_ClaptrapRescueTheSaltFlats,
		Base_ScavengerMachineGun,
		Base_ClaptrapRescueCrimsonFastness,
		Base_GetSomeAnswers,
		Base_FindTheEchoCommandConsole,
		Base_ReactiveTheEchoCommSystem,
		Base_FindSteele,
		Base_DestroyTheDestroyer,
		Base_BringTheVaultKeyToTannis,
		DLC1_WelcomingCommittee,
		DLC1_IsTheDoctorIn,
		DLC1_EggcellentOpportunity,
		DLC1_Pumpkinhead,
		DLC1_MissingHankReiss,
		DLC1_TKLives,
		DLC1_Brains1,
		DLC1_Brains2,
		DLC1_Brains3,
		DLC1_Brains4,
		DLC1_Brains5,
		DLC1_HouseOfTheNed,
		DLC1_LeaveItToTheProfessionals,
		DLC1_HereWeGoAgain,
		DLC1_ThereMayBeSomeSideEffects,
		DLC1_ItsAlive,
		DLC1_ThePack,
		DLC1_SecretsAndMysteries,
		DLC1_JakobsFodder,
		DLC1_Upsale,
		DLC1_HitchingARide,
		DLC1_ClaptrapRescueTheLumberYard,
		DLC1_ABridgeTooNed,
		DLC1_NightOfTheLivingNed,
		DLC1_NedsUndeadBabyNedsUndead,
		DLC2_ProveYourself,
		DLC3_ScooterButIDontEvenKnowHer,
		DLC3_BigCrimsonBrotherIsWatching,
		DLC3_WantedDead,
		DLC3_BoostTheMonster,
		DLC3_CoreCollection,
		DLC3_Greasemonkey,
		DLC3_YouveGotMoxxiRoadblock,
		DLC3_YouveGotMoxxiMoxxisRedLight,
		DLC3_PrisonBreakRoadWarrior,
		DLC3_RoadRage,
		DLC3_PowerLeech,
		DLC3_OMGAPC,
		DLC3_PurpleJuice,
		DLC3_LittlePeopleBigExperiments,
		DLC3_PrisonBreakOverTheWall,
		DLC3_ClaptrapRescueLockdownPalace,
		DLC3_PrisonBreakTryNotToGetShanked,
		DLC3_Rendezvous,
		DLC3_ThisBitchIsPayback,
		DLC3_CodeBreakerAnalysis,
		DLC3_CodeBreakerTimeIsBullets,
		DLC3_AthenaSetUpUsTheBomb,
		DLC3_DrifterLifter,
		DLC3_KnoxxedOut,
		DLC3_ThisBitchIsPaybackPt2,
		DLC3_ThrownForALoop,
		DLC3_BridgingTheGap,
		DLC3_Bugged,
		DLC3_StainRemoval,
		DLC3_LostLewts,
		DLC3_ArmoryAssault,
		DLC3_LootLarceny,
		DLC3_YouWillDie,
		DLC3_MopUp,
		DLC3_SuperMarcusSweep,
		DLC3_LocalTrouble,
		DLC3_ItsLikeChristmas,
		DLC3_CircleOfDutyNewRecruit,
		DLC3_CircleOfDutyCadet,
		DLC3_CircleOfDutyPrivate,
		DLC3_CircleOfDutyCorporal,
		DLC3_CircleOfDutySergeant,
		DLC3_CircleOfDutyMedalOfDuty,
		DLC4_AreYouFromTheseParts,
		DLC4_FightForYourRightToPartE,
		DLC4_PartsIsParts,
		DLC4_WeAllHaveOurPartToPlay,
		DLC4_APartOfSomethingLargerThanYourself,
		DLC4_NewContact,
		DLC4_LikeShootinRakkInABarrel,
		DLC4_SpaVsSpa,
		DLC4_OneUpmanPipp,
		DLC4_BurninRubber,
		DLC4_OperationTrapClaptrapTrapPhaseOne,
		DLC4_ItsATrapClap,
		DLC4_FingerLickinBad,
		DLC4_OperationTrapClaptrapTrapPhaseTwoIndustrialRevolution,
		DLC4_TakingStock,
		DLC4_OperationTrapClaptrapTrapPhaseThreeTripwired,
		DLC4_NotMyFault,
		DLC4_OldSpicy,
		DLC4_ElevenRakkAndSpices,
		DLC4_OperationTrapClaptrapTrapPhaseFourReboot,
		DLC4_HelpingIsItsOwnRewardWaitNoItIsnt,

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
	}

	/// <summary>
	/// Properties that are held by missions.
	/// </summary>
	public class Mission {
		/// <summary>
		/// An identifier of this specific mission.
		/// </summary>
		public MissionID ID;

		/// <summary>
		/// The internal name of this mission.
		/// </summary>
		public string InternalName {
			get { return InternalNames[ID]; }
			set { ID = InternalNames.Reverse()[value]; }
		}

		/// <summary>
		/// The in-game readable name of this mission.
		/// </summary>
		public string ReadableName { get { return ReadableNames[ID]; } }

		/// <summary>
		/// The status of this mission as a flag.
		/// </summary>
		public Int32 MissionStatusFlag;

		/// <summary>
		/// The status of this mission.
		/// </summary>
		public MissionStatus Status {
			get { return MissionStatusDefinitions[MissionStatusFlag]; }
			set { MissionStatusFlag = MissionStatusDefinitions.Reverse()[value]; }
		}

		/// <summary>
		/// An unknown variable; it appears to always be 0.
		/// </summary>
		public Int32 UnknownVariable2;

		/// <summary>
		/// An unknown variable; it appears to always be 0.
		/// </summary>
		public Int32 UnknownVariable3;

		/// <summary>
		/// The details of this mission (i.e. additional objectives).
		/// </summary>
		public List<MissionDetails> Details;

		/// <summary>
		/// Creates a blank mission.
		/// </summary>
		public Mission() {
			Details = new List<MissionDetails>();
		}

		/// <summary>
		/// Stores the details of a mission.
		/// </summary>
		public class MissionDetails {
			/// <summary>
			/// An unknown string.
			/// </summary>
			public string UnknownString;

			/// <summary>
			/// An unknown variable.
			/// </summary>
			public Int32 UnknownVariable;
		}

		/// <summary>
		/// Stores the status of a mission.
		/// </summary>
		public enum MissionStatus {
			/// <summary>
			/// This mission is not yet known to the player.
			/// </summary>
			Unknown,
			/// <summary>
			/// This mission is in progress.
			/// </summary>
			InProgress,
			/// <summary>
			/// This mission is ready to turn in.
			/// </summary>
			ReadyToTurnIn,
			/// <summary>
			/// This mission has been completed.
			/// </summary>
			Completed
		}

		/// <summary>
		/// Maps status flags to <see cref="MissionStatus"/>.
		/// </summary>
		public readonly Dictionary<Int32, MissionStatus> MissionStatusDefinitions = new Dictionary<Int32, MissionStatus> {
			{ 0, MissionStatus.Unknown },
			{ 1, MissionStatus.InProgress },
			{ 2, MissionStatus.ReadyToTurnIn },
			{ 4, MissionStatus.Completed },
		};

		/// <summary>
		/// Maps the mission IDs to their internal names.
		/// </summary>
		public readonly Dictionary<MissionID, string> InternalNames = new Dictionary<MissionID, string> {
			{ MissionID.Base_BigGameHunter, "dlc3_SideMissions.SideMissions.M_dlc3_UberBoss" },
			{ MissionID.Base_GettingLucky, "dlc3_MainMissions.MainMissions.M_dlc3_ActivateBridge" },
			{ MissionID.Base_PoweringTheFastTravelNetwork, "dlc3_SideMissions.SideMissions.M_dlc3_Drifter" },
			{ MissionID.Base_ScavengerRevolver, "dlc3_SideMissions.SideMissions.M_dlc3_Power" },
			{ MissionID.Base_FuelFeud, "dlc3_SideMissions.SideMissions.M_dlc3_LanceCommander01" },
			{ MissionID.Base_DeathRacePandora, "dlc3_MainMissions.MainMissions.M_dlc3_PrisonMrShank" },
			{ MissionID.Base_GhostsOfTheVault, "dlc3_SideMissions.SideMissions.M_dlc3_KnoxxECHOCollection" },
			{ MissionID.Base_WellTheresYourProblemRightThere, "dlc3_SideMissions.SideMissions.M_dlc3_ClaptrapRescue" },
			{ MissionID.Base_RoadWarriorsHotShots, "dlc3_SideMissions.SideMissions.M_dlc3_PowerCores" },
			{ MissionID.Base_RoadWarriorsBanditApocalypse, "dlc3_SideMissions.SideMissions.M_dlc3_Treasure" },
			{ MissionID.Base_PowerToThePeople, "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave3" },
			{ MissionID.Base_ClaptrapRescueNewHaven, "dlc3_SideMissions.SideMissions.M_dlc3_LanceCommander02" },
			{ MissionID.Base_KingTossing, "dlc3_MainMissions.MainMissions.M_dlc3_Roadblocks1" },
			{ MissionID.Base_CorrosiveCrystalHarvest, "dlc3_MainMissions.MainMissions.M_dlc3_GetLoot" },
			{ MissionID.Base_ClaptrapRescueTetanusWarren, "dlc3_SideMissions.SideMissions.M_dlc3_GetLoot02" },
			{ MissionID.Base_LikeAMothToFlame, "dlc3_SideMissions.SideMissions.M_dlc3_GetLoot03" },
			{ MissionID.Base_IsTKOK, "dlc3_SideMissions.SideMissions.M_dlc3_LoopDeLoop" },
			{ MissionID.Base_SeekOutTannis, "dlc3_SideMissions.SideMissions.M_dlc3_KillStuff02" },
			{ MissionID.Base_ScootersUsedCarParts, "dlc3_SideMissions.SideMissions.M_dlc3_DryWell" },
			{ MissionID.Base_UpToOurEars, "dlc3_SideMissions.SideMissions.M_dlc3_KillStuff01" },
			{ MissionID.Base_FirepowerAllSalesAreFinal, "dlc3_MainMissions.MainMissions.M_dlc3_MeetMoxxi" },
			{ MissionID.Base_FirepowerMarketCorrection, "dlc3_SideMissions.SideMissions.M_dlc3_Graffiti" },
			{ MissionID.Base_FirepowerPlightOfTheMiddleMan, "dlc3_SideMissions.SideMissions.M_dlc3_Hitman" },
			{ MissionID.Base_JacksOtherEye, "dlc3_CircleMissions.MainMissions.M_dlc3_CircleMeet" },
			{ MissionID.Base_ScavengerSubmachineGun, "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave2" },
			{ MissionID.Base_HiddenJournalRustCommonsWest, "dlc3_MainMissions.MainMissions.M_dlc3_FindCodeBunker" },
			{ MissionID.Base_MeetCrazyEarl, "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave5" },
			{ MissionID.Base_GetOffMyLawn, "dlc3_MainMissions.MainMissions.M_dlc3_BuildCar" },
			{ MissionID.Base_TodaysLessonHighExplosives, "dlc3_SideMissions.SideMissions.M_dlc3_Digistruct" },
			{ MissionID.Base_ClaptrapRescueScrapyard, "dlc3_SideMissions.SideMissions.M_dlc3_Gondola" },
			{ MissionID.Base_HairOfTheDog, "dlc3_MainMissions.MainMissions.M_dlc3_GetDetonator" },
			{ MissionID.Base_MissingPersons, "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave4" },
			{ MissionID.Base_TwoWrongsMakeARight, "dlc3_SideMissions.SideMissions.M_dlc3_Drones" },
			{ MissionID.Base_MiddleOfNowhereNoMoreInvestigate, "dlc3_MainMissions.MainMissions.M_dlc3_DestroyDepot" },
			{ MissionID.Base_MiddleOfNowhereNoMoreFusesReally, "dlc3_MainMissions.MainMissions.M_dlc3_FindCodeEarl" },
			{ MissionID.Base_MiddleOfNowhereNoMoreSmallFavor, "dlc3_SideMissions.SideMissions.M_dlc3_CPaws01" },
			{ MissionID.Base_MiddleOfNowhereNoMoreScootOnBack, "dlc3_MainMissions.MainMissions.M_dlc3_MeetInformant" },
			{ MissionID.Base_AltarEgoBurningHeresy, "dlc3_MainMissions.MainMissions.M_dlc3_Roadblocks2" },
			{ MissionID.Base_ScavengerShotgun, "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave1" },
			{ MissionID.Base_HiddenJournalRustCommonsEast, "dlc3_MainMissions.MainMissions.M_dlc3_PrisonInfiltrate" },
			{ MissionID.Base_CircleOfSlaughterMeatAndGreet, "dlc3_MainMissions.MainMissions.M_dlc3_MeetScooter" },
			{ MissionID.Base_CircleOfSlaughterRound1, "dlc3_MainMissions.MainMissions.M_dlc3_GetCarParts" },
			{ MissionID.Base_CircleOfSlaughterRound2, "dlc3_SideMissions.SideMissions.M_dlc3_Motorhead" },
			{ MissionID.Base_SkagsAtTheGate, "Z0_Missions.Missions.M_KillSkags_Zed" },
			{ MissionID.Base_TheNextPiece, "Z0_Missions.Missions.M_Saboteur" },
			{ MissionID.Base_EarlNeedsFoodBadly, "Z2_Missions.Missions.M_ReactivateEcho" },
			{ MissionID.Base_ClaptrapRescueKromsCanyon, "Z1_Missions.Missions.M_OldHaven_Smoked" },
			{ MissionID.Base_JaynistownSecretRendezvous, "Z1_Missions.Missions.M_HeathensInvestigate" },
			{ MissionID.Base_RelightTheBeacons, "Z1_Missions.Missions.M_RefugeeMissingPersons" },
			{ MissionID.Base_ABugProblem, "Z1_Missions.Missions.M_SlaughterWave2" },
			{ MissionID.Base_AltarEgoTheNewReligion, "Z0_Missions.Missions.M_MoeMarley" },
			{ MissionID.Base_AltarEgoGodlessMonsters, "I1_Missions.Missions.M_BanditConvoy01" },
			{ MissionID.Base_SmokeSignalsInvestigateOldHaven, "Z0_Missions.Missions.M_NineToesGetReward" },
			{ MissionID.Base_SmokeSignalsShutThemDown, "Z0_Missions.Missions.M_BuyGrenades" },
			{ MissionID.Base_BanditTreasureThreeCorpsesThreeKeys, "Z2_Missions.Missions.M_unknown" },
			{ MissionID.Base_BanditTreasureXMarksTheSpot, "Z1_Missions.Missions.M_BanditTreasureThree" },
			{ MissionID.Base_GreenThumb, "Z1_Missions.Missions.M_JaynisBrotherLove" },
			{ MissionID.Base_JaynistownABrothersLove, "Z0_Missions.Missions.M_MissingTools" },
			{ MissionID.Base_DumpsterDivingForGreatJustice, "Z0_Missions.Missions.M_KillSledge1" },
			{ MissionID.Base_JaynistownSpreadTheWord, "Z1_Missions.Missions.M_BridgesDamnTrespassers" },
			{ MissionID.Base_JaynistownGettingWhatsComingToYou, "Z0_Missions.Missions.M_Mothrak" },
			{ MissionID.Base_WantedFreshFish, "Z2_Missions.Missions.M_ClaptrapRescueLanceBunker" },
			{ MissionID.Base_IvegotASinkingFeeling, "Z1_Missions.Missions.M_FinalArtifact" },
			{ MissionID.Base_JaynistownCleaningUpYourMess, "Z1_Missions.Missions.M_SlaughterWave1" },
			{ MissionID.Base_ClaptrapRescueTrashCoast, "Z1_Missions.Missions.M_GreenCrystalHarvest" },
			{ MissionID.Base_BaitAndSwitch, "Z1_Missions.Missions.M_ClaptrapRescueOldHaven" },
			{ MissionID.Base_EarlsBestFriend, "Z2_Missions.Missions.M_ReturnKey" },
			{ MissionID.Base_HouseHunting, "Z0_Missions.Missions.M_ClaptrapRescueSafehouse" },
			{ MissionID.Base_AnotherPieceOfThePuzzle, "Z0_Missions.Missions.M_MeetAl" },
			{ MissionID.Base_NotWithoutMyClaptrap, "Z1_Missions.Missions.M_ABugProblem" },
			{ MissionID.Base_ClaptrapRescueOldHaven, "Z0_Missions.Missions.M_Scavenger1" },
			{ MissionID.Base_TheFinalPiece, "Z1_Missions.Missions.M_AnotherLittleSuprise" },
			{ MissionID.Base_ClaptrapRescueTheSaltFlats, "Z1_Missions.Missions.M_EarlsBestFriend" },
			{ MissionID.Base_ScavengerMachineGun, "Z1_Missions.Missions.M_GreenThumb" },
			{ MissionID.Base_ClaptrapRescueCrimsonFastness, "Z1_Missions.Missions.M_JaynisUnintendedConseq" },
			{ MissionID.Base_GetSomeAnswers, "Z0_Missions.Missions.M_BackToZed" },
			{ MissionID.Base_FindTheEchoCommandConsole, "Z1_Missions.Missions.M_ClaptrapRescueCanyon" },
			{ MissionID.Base_ReactiveTheEchoCommSystem, "I1_Missions.Missions.M_RoadBlocks" },
			{ MissionID.Base_FindSteele, "I1_Missions.Missions.M_Scavenger3" },
			{ MissionID.Base_DestroyTheDestroyer, "Z1_Missions.Missions.M_JaynisSecretRendezvous" },
			{ MissionID.Base_BringTheVaultKeyToTannis, "Z1_Missions.Missions.M_GunboatSabotage" },
			{ MissionID.DLC1_WelcomingCommittee, "Z1_Missions.Missions.M_AssassinateJack" },
			{ MissionID.DLC1_IsTheDoctorIn, "Z0_Missions.Missions.M_OwedMoneyDebt" },
			{ MissionID.DLC1_EggcellentOpportunity, "Z1_Missions.Missions.M_RelightTheBeacons" },
			{ MissionID.DLC1_Pumpkinhead, "Z1_Missions.Missions.M_ThirdFragment" },
			{ MissionID.DLC1_MissingHankReiss, "Z1_Missions.Missions.M_ClaptrapRescueScrapyard" },
			{ MissionID.DLC1_TKLives, "Z0_Missions.Missions.M_BloodOnTheTires" },
			{ MissionID.DLC1_Brains1, "Z1_Missions.Missions.M_TurnOnTheStank" },
			{ MissionID.DLC1_Brains2, "Z1_Missions.Missions.M_Miscommunication_ReturnToHelena" },
			{ MissionID.DLC1_Brains3, "Z0_Missions.Missions.M_FixHealthVending" },
			{ MissionID.DLC1_Brains4, "Z1_Missions.Missions.M_BaitResearch" },
			{ MissionID.DLC1_Brains5, "Z0_Missions.Missions.M_TheSkulls" },
			{ MissionID.DLC1_HouseOfTheNed, "Z0_Missions.Missions.M_RecoverLostData_1" },
			{ MissionID.DLC1_LeaveItToTheProfessionals, "Z1_Missions.Missions.M_JaynisSpreadTheWord" },
			{ MissionID.DLC1_HereWeGoAgain, "Z1_Missions.Missions.M_Miscommunication_SmallFavor" },
			{ MissionID.DLC1_ThereMayBeSomeSideEffects, "Z0_Missions.Missions.M_KillSledge2" },
			{ MissionID.DLC1_ItsAlive, "I1_Missions.Missions.M_RepairGasPipes" },
			{ MissionID.DLC1_ThePack, "Z0_Missions.Missions.M_TravelToNH" },
			{ MissionID.DLC1_SecretsAndMysteries, "I1_Missions.Missions.M_OpeningTheRaceTrack" },
			{ MissionID.DLC1_JakobsFodder, "Z1_Missions.Missions.M_Scavenger4" },
			{ MissionID.DLC1_Upsale, "Z1_Missions.Missions.M_ReachTheSaltFlats" },
			{ MissionID.DLC1_HitchingARide, "Z0_Missions.Missions.M_Scavenger2" },
			{ MissionID.DLC1_ClaptrapRescueTheLumberYard, "Z0_Missions.Missions.M_RakkDebris" },
			{ MissionID.DLC1_ABridgeTooNed, "Z0_Missions.Missions.M_RakkMenace" },
			{ MissionID.DLC1_NightOfTheLivingNed, "Z0_Missions.Missions.M_TKHasMoreWork" },
			{ MissionID.DLC1_NedsUndeadBabyNedsUndead, "Z1_Missions.Missions.M_HeathensGodlessMonsters" },
			{ MissionID.DLC2_ProveYourself, "Z2_Missions.Missions.M_RecoverLostData_3" },
			{ MissionID.DLC3_ScooterButIDontEvenKnowHer, "I1_Missions.Missions.M_BanditConvoy03" },
			{ MissionID.DLC3_BigCrimsonBrotherIsWatching, "Z0_Missions.Missions.M_BountyBoard" },
			{ MissionID.DLC3_WantedDead, "I2_Missions.Missions.M_Scavenger6" },
			{ MissionID.DLC3_BoostTheMonster, "Z0_Missions.Missions.M_AccessStores" },
			{ MissionID.DLC3_CoreCollection, "Z0_Missions.Missions.M_BanditPresence1" },
			{ MissionID.DLC3_Greasemonkey, "Z1_Missions.Missions.M_SlaughterMeatAndGreet" },
			{ MissionID.DLC3_YouveGotMoxxiRoadblock, "Z0_Missions.Missions.M_JumpTheGap" },
			{ MissionID.DLC3_YouveGotMoxxiMoxxisRedLight, "I1_Missions.Missions.M_FuelSupply" },
			{ MissionID.DLC3_PrisonBreakRoadWarrior, "Z0_Missions.Missions.M_OwedMoneyInvestigate" },
			{ MissionID.DLC3_RoadRage, "Z1_Missions.Missions.M_KingWeeWee" },
			{ MissionID.DLC3_PowerLeech, "Z0_Missions.Missions.M_RefugeeTwoWrongs" },
			{ MissionID.DLC3_OMGAPC, "I1_Missions.Missions.M_Assassinate_SkagZilla" },
			{ MissionID.DLC3_PurpleJuice, "Z1_Missions.Missions.M_FirepowerPlans" },
			{ MissionID.DLC3_LittlePeopleBigExperiments, "Z0_Missions.Missions.M_KillBandits" },
			{ MissionID.DLC3_PrisonBreakOverTheWall, "Z0_Missions.Missions.M_RepairClapTrap_02" },
			{ MissionID.DLC3_ClaptrapRescueLockdownPalace, "Z1_Missions.Missions.M_BridgesGetABeer" },
			{ MissionID.Base_SledgeMeetShep, "Z0_Missions.Missions.M_MeetShep" },
			{ MissionID.DLC3_Rendezvous, "Z0_Missions.Missions.M_SubstationKey" },
			{ MissionID.DLC3_ThisBitchIsPayback, "Z1_Missions.Missions.M_NewHavenGenerators" },
			{ MissionID.DLC3_CodeBreakerAnalysis, "Z1_Missions.Missions.M_RecoverLostData_2" },
			{ MissionID.DLC3_CodeBreakerTimeIsBullets, "Z1_Missions.Missions.M_BanditTreasureXMarks" },
			{ MissionID.DLC3_AthenaSetUpUsTheBomb, "Z1_Missions.Missions.M_SeekTannis" },
			{ MissionID.DLC3_DrifterLifter, "Z1_Missions.Missions.M_AltarEgo" },
			{ MissionID.DLC3_KnoxxedOut, "Z0_Missions.Missions.M_HarvestCrystals_Electrical" },
			{ MissionID.DLC3_ThisBitchIsPaybackPt2, "Z0_Missions.Missions.M_FixVSS" },
			{ MissionID.DLC3_ThrownForALoop, "Z0_Missions.Missions.M_ExterminateSkag" },
			{ MissionID.DLC3_BridgingTheGap, "Z1_Missions.Missions.M_ScootersUsedCarParts" },
			{ MissionID.DLC3_Bugged, "Z0_Missions.Missions.M_GetMyLegBack" },
			{ MissionID.DLC3_StainRemoval, "Z1_Missions.Missions.M_FindEarl" },
			{ MissionID.DLC3_LostLewts, "Z1_Missions.Missions.M_SkrappyNeedsFood" },
			{ MissionID.DLC3_ArmoryAssault, "Z1_Missions.Missions.M_JaynisCleaningUp" },
			{ MissionID.DLC3_LootLarceny, "I1_Missions.Missions.M_AbandonedDig" },
			{ MissionID.DLC3_YouWillDie, "Z2_Missions.Missions.M_ClaptrapRescueSanctuary" },
			{ MissionID.DLC3_MopUp, "Z1_Missions.Missions.M_FirepowerWeapons" },
			{ MissionID.DLC3_SuperMarcusSweep, "Z1_Missions.Missions.M_SquatterHouseHunting" },
			{ MissionID.DLC3_LocalTrouble, "I1_Missions.Missions.M_Powerlines" },
			{ MissionID.DLC3_ItsLikeChristmas, "Z1_Missions.Missions.M_Scavenger5" },
			{ MissionID.DLC3_CircleOfDutyNewRecruit, "Z1_Missions.Missions.M_FirepowerMunitions" },
			{ MissionID.DLC3_CircleOfDutyCadet, "Z2_Missions.Missions.M_FindEcho" },
			{ MissionID.DLC3_CircleOfDutyPrivate, "Z1_Missions.Missions.M_OldHaven_Investigate" },
			{ MissionID.DLC3_CircleOfDutyCorporal, "Z1_Missions.Missions.M_EarlBanditOutpostDestroyed" },
			{ MissionID.DLC3_CircleOfDutySergeant, "Z1_Missions.Missions.M_NewHavenDefenses" },
			{ MissionID.DLC3_CircleOfDutyMedalOfDuty, "Z0_Missions.Missions.M_CircleMeatAndGreet" },
			{ MissionID.DLC4_AreYouFromTheseParts, "Z0_Missions.Missions.M_GatherSeeds" },
			{ MissionID.DLC4_FightForYourRightToPartE, "Z0_Missions.Missions.M_OpenGatetoSkag" },
			{ MissionID.DLC4_PartsIsParts, "Z0_Missions.Missions.M_InvestigateVSS" },
			{ MissionID.DLC4_WeAllHaveOurPartToPlay, "Z1_Missions.Missions.M_Miscommunication_Investigate" },
			{ MissionID.DLC4_APartOfSomethingLargerThanYourself, "Z1_Missions.Missions.M_Miscommunication_FindParts" },
			{ MissionID.DLC4_NewContact, "Z1_Missions.Missions.M_WantedFreshFish" },
			{ MissionID.DLC4_LikeShootinRakkInABarrel, "Z0_Missions.Missions.M_CircleOfDeath03" },
			{ MissionID.DLC4_SpaVsSpa, "Z0_Missions.Missions.M_CircleOfDeath02" },
			{ MissionID.DLC4_OneUpmanPipp, "Z1_Missions.Missions.M_ClaptrapRescueNewHaven" },
			{ MissionID.DLC4_BurninRubber, "Z0_Missions.Missions.M_CircleOfDeath01" },
			{ MissionID.Base_FreshOffTheBus, "Z0_Missions.Missions.M_IntroStateSaver" },
			{ MissionID.DLC4_ItsATrapClap, "Z1_Missions.Missions.M_ClaptrapRescueTrashCave" },
			{ MissionID.DLC4_FingerLickinBad, "Z0_Missions.Missions.M_WindTurbine_Activate" },
			{ MissionID.DLC4_OperationTrapClaptrapTrapPhaseTwoIndustrialRevolution, "Z2_Missions.Missions.M_FindSteele" },
			{ MissionID.DLC4_TakingStock, "Z1_Missions.Missions.M_SlaughterWave3" },
			{ MissionID.DLC4_OperationTrapClaptrapTrapPhaseThreeTripwired, "Z1_Missions.Missions.M_JaynisGettingWhatsComing" },
			{ MissionID.DLC4_NotMyFault, "Z1_Missions.Missions.M_ClaptrapRescueTrashCoast" },
			{ MissionID.DLC4_OldSpicy, "Z0_Missions.Missions.M_ClaptrapRescueLostCave" },
			{ MissionID.DLC4_ElevenRakkAndSpices, "Z2_Missions.Missions.M_FindTheVault" },
			{ MissionID.DLC4_OperationTrapClaptrapTrapPhaseFourReboot, "dlc1_missions.MainMissions.M_dlc1_KillZombieNed" },
			{ MissionID.DLC4_HelpingIsItsOwnRewardWaitNoItIsnt, "dlc1_missions.SideMissions.M_dlc1_TKBrains3" },
			{ MissionID.Base_JaynistownUnintendedConsequences, "dlc1_missions.MainMissions.M_dlc1_KillNed" },
			{ MissionID.Base_SledgeBattleForTheBadlands, "dlc1_missions.SideMissions.M_dlc1_BountyHunterLogs_Mill" },
			{ MissionID.Base_BlindingNineToes, "dlc1_missions.SideMissions.M_dlc1_TKBrains2" },
			{ MissionID.Base_BoneHeadsTheft, "dlc1_missions.SideMissions.M_dlc1_RepairClaptrap" },
			{ MissionID.Base_BrakingWind, "dlc1_missions.SideMissions.M_dlc1_FrankenBill" },
			{ MissionID.Base_ByTheSeedsOfYourPants, "dlc1_missions.MainMissions.M_dlc1_DefendTown" },
			{ MissionID.Base_CatchARide, "dlc1_missions.MainMissions.M_dlc1_NedLab" },
			{ MissionID.Base_CircleOfDeathFinalRound, "dlc1_missions.MainMissions.M_dlc1_LowerBridge" },
			{ MissionID.Base_CircleOfDeathMeatAndGreet, "dlc1_missions.SideMissions.M_dlc1_PumpkinHead" },
			{ MissionID.Base_CircleOfDeathRound1, "dlc1_missions.SideMissions.M_dlc1_LogCollection" },
			{ MissionID.Base_CircleOfDeathRound2, "dlc1_missions.MainMissions.M_dlc1_NedsNote" },
			{ MissionID.Base_ClaptrapRescue, "dlc1_missions.SideMissions.M_dlc1_TKBrains4" },
			{ MissionID.Base_ClaptrapRescueSafeHouse, "dlc1_missions.SideMissions.M_dlc1_TKBrains1" },
			{ MissionID.Base_ClaptrapRescueTheLostCave, "dlc1_missions.SideMissions.M_dlc1_TKBrains5" },
			{ MissionID.Base_FindBruceMcClane, "dlc1_missions.SideMissions.M_dlc1_Eggs" },
			{ MissionID.Base_FixerUpper, "dlc1_missions.SideMissions.M_dlc1_FixJakobsVending" },
			{ MissionID.DLC4_OperationTrapClaptrapTrapPhaseOne, "dlc1_missions.SideMissions.M_dlc1_FindZombieTK" },
			{ MissionID.Base_GetALittleBloodOnTheTires, "dlc1_missions.MainMissions.M_dlc1_Wereskag" },
			{ MissionID.Base_GetTheFlockOuttaHere, "dlc1_missions.MainMissions.M_dlc1_ReturnToIsland" },
			{ MissionID.Base_GotGrenades, "dlc1_missions.MainMissions.M_dlc1_TellJakobs" },
			{ MissionID.Base_HiddenJournalTheAridBadlands, "dlc1_missions.SideMissions.M_dlc1_WereskagPack" },
			{ MissionID.Base_InsultToInjury, "dlc1_missions.MainMissions.M_dlc1_MeetNed" },
			{ MissionID.Base_JobHunting, "dlc1_missions.SideMissions.M_dlc1_BountyHunterLogs_priest" },
			{ MissionID.Base_LeavingFyrestore, "dlc2_missions.Missions.M_ClearArenas" },
			{ MissionID.Base_NineToesMeetTKBaha, "DLC4_Tartarus_Stat_Missions.SideMissions.M_dlc4_Repair_Trap_Clap" },
			{ MissionID.Base_NineToesTakeHimDown, "DLC4_Sanders_Gorge_Missions.MainMissions.M_dlc4_Eleven_Rakks_Spices" },
			{ MissionID.Base_NineToesTimeToCollect, "DLC4_Sanders_Gorge_Missions.MainMissions.M_dlc4_Finger_Lickin_Bad" },
			{ MissionID.Base_NineToesTKsFood, "DLC4_Tartarus_Stat_Missions.MainMissions.M_dlc4_M7_Helping_is_its_own_reward" },
			{ MissionID.Base_ProductRecall, "DLC4_D_Faults_Missions.SideMissions.M_DLC4_DFault" },
			{ MissionID.Base_ReturnToZed, "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_TannisParts4" },
			{ MissionID.Base_ScavengerCombatRifle, "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_Burn_Rubber" },
			{ MissionID.Base_ScavengerSniperRifle, "DLC4_Tartarus_Stat_Missions.MainMissions.M_dlc4_New_Contact" },
			{ MissionID.Base_ScheminThatSabotage, "DLC4_D_Faults_Missions.SideMissions.M_DLC4_TakingStock" },
			{ MissionID.Base_ShockCrystalHarvest, "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_TannisParts5" },
			{ MissionID.Base_CircleOfSlaughterFinalRound, "DLC4_Tartarus_Stat_Missions.SideMissions.M_side_dlc4_OneUpmanPipp" },
			{ MissionID.DLC3_PrisonBreakTryNotToGetShanked, "DLC4_D_Faults_Missions.MainMissions.M_DLC4_OTCT_Phase2" },
			{ MissionID.Base_SledgeTheMineKey, "DLC4_Tartarus_Stat_Missions.SideMissions.M_dlc4_Spa_Vs_Spa" },
			{ MissionID.Base_SledgeToTheSafeHouse, "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_TannisParts3" },
			{ MissionID.Base_TheDoctorIsIn, "DLC4_SS_Canyon_Missions.MainMissions.M_DLC4_TripWIRED" },
			{ MissionID.Base_TheLegendOfMoeAndMarley, "DLC4_Wayward_Pass_Missions.MainMissions.M_dlc4_OTCT_Reboot" },
			{ MissionID.Base_ThePissWashHurdle, "DLC4_SS_Canyon_Missions.SideMissions.M_side_dlc4_OldSpicy" },
			{ MissionID.Base_TKHasMoreWork, "DLC4_Sanders_Gorge_Missions.MainMissions.M_dlc4_OTCT_Phase_One" },
			{ MissionID.Base_TKsLifeAndLimb, "DLC4_Tartarus_Stat_Missions.SideMissions.M_dlc4_Shooting_Rakks_Barrel" },
			{ MissionID.Base_WhatHitTheFan, "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_TannisParts2" },
			{ MissionID.Base_WhyAreTheyHere, "DLC4_Hyperion_Dump_Missions.MainMissions.M_dlc4_AreyoufromtheseParts" }
		};


		/// <summary>
		/// Maps the mission IDs to their readable in-game names.
		/// </summary>
		public readonly Dictionary<MissionID, string> ReadableNames = new Dictionary<MissionID, string> {
			{ MissionID.Base_FreshOffTheBus, "Fresh Off The Bus" },
			{ MissionID.Base_TheDoctorIsIn, "The Doctor Is In" },
			{ MissionID. Base_SkagsAtTheGate, "Skags At The Gate" },
			{ MissionID.Base_ClaptrapRescue, "Claptrap Rescue" },
			{ MissionID.Base_FixerUpper, "Fix'er Upper" },
			{ MissionID.Base_BlindingNineToes, "Blinding Nine-Toes" },
			{ MissionID.Base_NineToesMeetTKBaha, "Nine-Toes: Meet T.K. Baha" },
			{ MissionID.Base_NineToesTKsFood, "Nine-Toes: T.K.'s Food" },
			{ MissionID.Base_GotGrenades, "Got Grenades?" },
			{ MissionID.Base_NineToesTakeHimDown, "Nine-Toes: Take Him Down" },
			{ MissionID.Base_NineToesTimeToCollect, "Nine-Toes: Time To Collect" },
			{ MissionID.Base_JobHunting, "Job Hunting" },
			{ MissionID.Base_TKHasMoreWork, "T.K. Has More Work" },
			{ MissionID.Base_WhyAreTheyHere, "Why Are They Here?" },
			{ MissionID.Base_TKsLifeAndLimb, "T.K.'s Life And Limb" },
			{ MissionID.Base_ByTheSeedsOfYourPants, "By The Seeds Of Your Pants" },
			{ MissionID.Base_CatchARide, "Catch-A-Ride" },
			{ MissionID.Base_BoneHeadsTheft, "Bone Head's Theft" },
			{ MissionID.Base_GetALittleBloodOnTheTires, "Get A Little Blood On The Tires" },
			{ MissionID.Base_ThePissWashHurdle, "The Piss Wash Hurdle" },
			{ MissionID.Base_HiddenJournalTheAridBadlands, "Hidden Journal: The Arid Badlands" },
			{ MissionID.Base_ClaptrapRescueTheLostCave, "Claptrap Rescue: The Lost Cave" },
			{ MissionID.Base_ShockCrystalHarvest, "Shock Crystal Harvest" },
			{ MissionID.Base_ReturnToZed, "Return To Zed" },
			{ MissionID.Base_SledgeMeetShep, "Sledge: Meet Shep" },
			{ MissionID.Base_BrakingWind, "Braking Wind" },
			{ MissionID.Base_GetTheFlockOuttaHere, "Get The Flock Outta Here" },
			{ MissionID.Base_SledgeTheMineKey, "Sledge: The Mine Key" },
			{ MissionID.Base_ScavengerSniperRifle, "Scavenger: Sniper Rifle" },
			{ MissionID.Base_TheLegendOfMoeAndMarley, "The Legend Of Moe and Marley" },
			{ MissionID.Base_CircleOfDeathMeatAndGreet, "Circle Of Death: Meat And Greet" },
			{ MissionID.Base_CircleOfDeathRound1, "Circle Of Death: Round 1" },
			{ MissionID.Base_CircleOfDeathRound2, "Circle Of Death: Round 2" },
			{ MissionID.Base_CircleOfDeathFinalRound, "Circle Of Death: Final Round" },
			{ MissionID.Base_SledgeToTheSafeHouse, "Sledge: To The Safe House" },
			{ MissionID.Base_ClaptrapRescueSafeHouse, "Claptrap Rescue: Safe House" },
			{ MissionID.Base_ScavengerCombatRifle, "Scavenger: Combat Rifle" },
			{ MissionID.Base_WhatHitTheFan, "What Hit The Fan" },
			{ MissionID.Base_SledgeBattleForTheBadlands, "Sledge: Battle For The Badlands" },
			{ MissionID.Base_FindBruceMcClane, "Find Bruce McClane" },
			{ MissionID.Base_ProductRecall, "Product Recall" },
			{ MissionID.Base_InsultToInjury, "Insult To Injury" },
			{ MissionID.Base_ScheminThatSabotage, "Schemin' That Sabotage" },
			{ MissionID.Base_LeavingFyrestore, "Leaving Fyrestone" },
			{ MissionID.Base_BigGameHunter, "Unknown mission 045" },
			{ MissionID.Base_GettingLucky, "Unknown mission 046" },
			{ MissionID.Base_PoweringTheFastTravelNetwork, "Unknown mission 047" },
			{ MissionID.Base_ScavengerRevolver, "Unknown mission 048" },
			{ MissionID.Base_FuelFeud, "Unknown mission 049" },
			{ MissionID.Base_DeathRacePandora, "Unknown mission 050" },
			{ MissionID.Base_GhostsOfTheVault, "Unknown mission 051" },
			{ MissionID.Base_WellTheresYourProblemRightThere, "Unknown mission 052" },
			{ MissionID.Base_RoadWarriorsHotShots, "Unknown mission 053" },
			{ MissionID.Base_RoadWarriorsBanditApocalypse, "Unknown mission 054" },
			{ MissionID.Base_PowerToThePeople, "Unknown mission 055" },
			{ MissionID.Base_ClaptrapRescueNewHaven, "Unknown mission 056" },
			{ MissionID.Base_KingTossing, "Unknown mission 057" },
			{ MissionID.Base_CorrosiveCrystalHarvest, "Unknown mission 058" },
			{ MissionID.Base_ClaptrapRescueTetanusWarren, "Unknown mission 059" },
			{ MissionID.Base_LikeAMothToFlame, "Unknown mission 060" },
			{ MissionID.Base_IsTKOK, "Unknown mission 061" },
			{ MissionID.Base_SeekOutTannis, "Unknown mission 062" },
			{ MissionID.Base_ScootersUsedCarParts, "Unknown mission 063" },
			{ MissionID.Base_UpToOurEars, "Unknown mission 064" },
			{ MissionID.Base_FirepowerAllSalesAreFinal, "Unknown mission 065" },
			{ MissionID.Base_FirepowerMarketCorrection, "Unknown mission 066" },
			{ MissionID.Base_FirepowerPlightOfTheMiddleMan, "Unknown mission 067" },
			{ MissionID.Base_JacksOtherEye, "Unknown mission 068" },
			{ MissionID.Base_ScavengerSubmachineGun, "Unknown mission 069" },
			{ MissionID.Base_HiddenJournalRustCommonsWest, "Unknown mission 070" },
			{ MissionID.Base_MeetCrazyEarl, "Unknown mission 071" },
			{ MissionID.Base_GetOffMyLawn, "Unknown mission 072" },
			{ MissionID.Base_TodaysLessonHighExplosives, "Unknown mission 073" },
			{ MissionID.Base_ClaptrapRescueScrapyard, "Unknown mission 074" },
			{ MissionID.Base_HairOfTheDog, "Unknown mission 075" },
			{ MissionID.Base_MissingPersons, "Unknown mission 076" },
			{ MissionID.Base_TwoWrongsMakeARight, "Unknown mission 077" },
			{ MissionID.Base_MiddleOfNowhereNoMoreInvestigate, "Unknown mission 078" },
			{ MissionID.Base_MiddleOfNowhereNoMoreFusesReally, "Unknown mission 079" },
			{ MissionID.Base_MiddleOfNowhereNoMoreSmallFavor, "Unknown mission 080" },
			{ MissionID.Base_MiddleOfNowhereNoMoreScootOnBack, "Unknown mission 081" },
			{ MissionID.Base_AltarEgoBurningHeresy, "Unknown mission 082" },
			{ MissionID.Base_ScavengerShotgun, "Unknown mission 083" },
			{ MissionID.Base_HiddenJournalRustCommonsEast, "Unknown mission 084" },
			{ MissionID.Base_CircleOfSlaughterMeatAndGreet, "Unknown mission 085" },
			{ MissionID.Base_CircleOfSlaughterRound1, "Unknown mission 086" },
			{ MissionID.Base_CircleOfSlaughterRound2, "Unknown mission 087" },
			{ MissionID.Base_CircleOfSlaughterFinalRound, "Unknown mission 088" },
			{ MissionID.Base_TheNextPiece, "Unknown mission 089" },
			{ MissionID.Base_EarlNeedsFoodBadly, "Unknown mission 090" },
			{ MissionID.Base_ClaptrapRescueKromsCanyon, "Unknown mission 091" },
			{ MissionID.Base_JaynistownSecretRendezvous, "Unknown mission 092" },
			{ MissionID.Base_RelightTheBeacons, "Unknown mission 093" },
			{ MissionID.Base_ABugProblem, "Unknown mission 094" },
			{ MissionID.Base_AltarEgoTheNewReligion, "Unknown mission 095" },
			{ MissionID.Base_AltarEgoGodlessMonsters, "Unknown mission 096" },
			{ MissionID.Base_SmokeSignalsInvestigateOldHaven, "Unknown mission 097" },
			{ MissionID.Base_SmokeSignalsShutThemDown, "Unknown mission 098" },
			{ MissionID.Base_BanditTreasureThreeCorpsesThreeKeys, "Unknown mission 099" },
			{ MissionID.Base_BanditTreasureXMarksTheSpot, "Unknown mission 100" },
			{ MissionID.Base_GreenThumb, "Unknown mission 101" },
			{ MissionID.Base_JaynistownABrothersLove, "Unknown mission 102" },
			{ MissionID.Base_DumpsterDivingForGreatJustice, "Unknown mission 103" },
			{ MissionID.Base_JaynistownSpreadTheWord, "Unknown mission 104" },
			{ MissionID.Base_JaynistownGettingWhatsComingToYou, "Unknown mission 105" },
			{ MissionID.Base_WantedFreshFish, "Unknown mission 106" },
			{ MissionID.Base_IvegotASinkingFeeling, "Unknown mission 107" },
			{ MissionID.Base_JaynistownUnintendedConsequences, "Unknown mission 216" },
			{ MissionID.Base_JaynistownCleaningUpYourMess, "Unknown mission 108" },
			{ MissionID.Base_ClaptrapRescueTrashCoast, "Unknown mission 109" },
			{ MissionID.Base_BaitAndSwitch, "Unknown mission 110" },
			{ MissionID.Base_EarlsBestFriend, "Unknown mission 111" },
			{ MissionID.Base_HouseHunting, "Unknown mission 112" },
			{ MissionID.Base_AnotherPieceOfThePuzzle, "Unknown mission 113" },
			{ MissionID.Base_NotWithoutMyClaptrap, "Unknown mission 114" },
			{ MissionID.Base_ClaptrapRescueOldHaven, "Unknown mission 115" },
			{ MissionID.Base_TheFinalPiece, "Unknown mission 116" },
			{ MissionID.Base_ClaptrapRescueTheSaltFlats, "Unknown mission 117" },
			{ MissionID.Base_ScavengerMachineGun, "Unknown mission 118" },
			{ MissionID.Base_ClaptrapRescueCrimsonFastness, "Unknown mission 119" },
			{ MissionID.Base_GetSomeAnswers, "Unknown mission 120" },
			{ MissionID.Base_FindTheEchoCommandConsole, "Unknown mission 121" },
			{ MissionID.Base_ReactiveTheEchoCommSystem, "Unknown mission 122" },
			{ MissionID.Base_FindSteele, "Unknown mission 123" },
			{ MissionID.Base_DestroyTheDestroyer, "Unknown mission 124" },
			{ MissionID.Base_BringTheVaultKeyToTannis, "Unknown mission 125" },
			{ MissionID.DLC1_WelcomingCommittee, "Unknown mission 126" },
			{ MissionID.DLC1_IsTheDoctorIn, "Unknown mission 127" },
			{ MissionID.DLC1_EggcellentOpportunity, "Unknown mission 128" },
			{ MissionID.DLC1_Pumpkinhead, "Unknown mission 129" },
			{ MissionID.DLC1_MissingHankReiss, "Unknown mission 130" },
			{ MissionID.DLC1_TKLives, "Unknown mission 131" },
			{ MissionID.DLC1_Brains1, "Unknown mission 132" },
			{ MissionID.DLC1_Brains2, "Unknown mission 133" },
			{ MissionID.DLC1_Brains3, "Unknown mission 134" },
			{ MissionID.DLC1_Brains4, "Unknown mission 135" },
			{ MissionID.DLC1_Brains5, "Unknown mission 136" },
			{ MissionID.DLC1_HouseOfTheNed, "Unknown mission 137" },
			{ MissionID.DLC1_LeaveItToTheProfessionals, "Unknown mission 138" },
			{ MissionID.DLC1_HereWeGoAgain, "Unknown mission 139" },
			{ MissionID.DLC1_ThereMayBeSomeSideEffects, "Unknown mission 140" },
			{ MissionID.DLC1_ItsAlive, "Unknown mission 141" },
			{ MissionID.DLC1_ThePack, "Unknown mission 142" },
			{ MissionID.DLC1_SecretsAndMysteries, "Unknown mission 143" },
			{ MissionID.DLC1_JakobsFodder, "Unknown mission 144" },
			{ MissionID.DLC1_Upsale, "Unknown mission 145" },
			{ MissionID.DLC1_HitchingARide, "Unknown mission 146" },
			{ MissionID.DLC1_ClaptrapRescueTheLumberYard, "Unknown mission 147" },
			{ MissionID.DLC1_ABridgeTooNed, "Unknown mission 148" },
			{ MissionID.DLC1_NightOfTheLivingNed, "Unknown mission 149" },
			{ MissionID.DLC1_NedsUndeadBabyNedsUndead, "Unknown mission 150" },
			{ MissionID.DLC2_ProveYourself, "Unknown mission 151" },
			{ MissionID.DLC3_ScooterButIDontEvenKnowHer, "Unknown mission 152" },
			{ MissionID.DLC3_BigCrimsonBrotherIsWatching, "Unknown mission 153" },
			{ MissionID.DLC3_WantedDead, "Unknown mission 154" },
			{ MissionID.DLC3_BoostTheMonster, "Unknown mission 155" },
			{ MissionID.DLC3_CoreCollection, "Unknown mission 156" },
			{ MissionID.DLC3_Greasemonkey, "Unknown mission 157" },
			{ MissionID.DLC3_YouveGotMoxxiRoadblock, "Unknown mission 158" },
			{ MissionID.DLC3_YouveGotMoxxiMoxxisRedLight, "Unknown mission 159" },
			{ MissionID.DLC3_PrisonBreakRoadWarrior, "Unknown mission 160" },
			{ MissionID.DLC3_RoadRage, "Unknown mission 161" },
			{ MissionID.DLC3_PowerLeech, "Unknown mission 162" },
			{ MissionID.DLC3_OMGAPC, "Unknown mission 163" },
			{ MissionID.DLC3_PurpleJuice, "Unknown mission 164" },
			{ MissionID.DLC3_LittlePeopleBigExperiments, "Unknown mission 165" },
			{ MissionID.DLC3_PrisonBreakOverTheWall, "Unknown mission 166" },
			{ MissionID.DLC3_ClaptrapRescueLockdownPalace, "Unknown mission 167" },
			{ MissionID.DLC3_PrisonBreakTryNotToGetShanked, "Unknown mission 168" },
			{ MissionID.DLC3_Rendezvous, "Unknown mission 169" },
			{ MissionID.DLC3_ThisBitchIsPayback, "Unknown mission 170" },
			{ MissionID.DLC3_CodeBreakerAnalysis, "Unknown mission 171" },
			{ MissionID.DLC3_CodeBreakerTimeIsBullets, "Unknown mission 172" },
			{ MissionID.DLC3_AthenaSetUpUsTheBomb, "Unknown mission 173" },
			{ MissionID.DLC3_DrifterLifter, "Unknown mission 174" },
			{ MissionID.DLC3_KnoxxedOut, "Unknown mission 175" },
			{ MissionID.DLC3_ThisBitchIsPaybackPt2, "Unknown mission 176" },
			{ MissionID.DLC3_ThrownForALoop, "Unknown mission 177" },
			{ MissionID.DLC3_BridgingTheGap, "Unknown mission 178" },
			{ MissionID.DLC3_Bugged, "Unknown mission 179" },
			{ MissionID.DLC3_StainRemoval, "Unknown mission 180" },
			{ MissionID.DLC3_LostLewts, "Unknown mission 181" },
			{ MissionID.DLC3_ArmoryAssault, "Unknown mission 182" },
			{ MissionID.DLC3_LootLarceny, "Unknown mission 183" },
			{ MissionID.DLC3_YouWillDie, "Unknown mission 184" },
			{ MissionID.DLC3_MopUp, "Unknown mission 185" },
			{ MissionID.DLC3_SuperMarcusSweep, "Unknown mission 186" },
			{ MissionID.DLC3_LocalTrouble, "Unknown mission 187" },
			{ MissionID.DLC3_ItsLikeChristmas, "Unknown mission 188" },
			{ MissionID.DLC3_CircleOfDutyNewRecruit, "Unknown mission 189" },
			{ MissionID.DLC3_CircleOfDutyCadet, "Unknown mission 190" },
			{ MissionID.DLC3_CircleOfDutyPrivate, "Unknown mission 191" },
			{ MissionID.DLC3_CircleOfDutyCorporal, "Unknown mission 192" },
			{ MissionID.DLC3_CircleOfDutySergeant, "Unknown mission 193" },
			{ MissionID.DLC3_CircleOfDutyMedalOfDuty, "Unknown mission 194" },
			{ MissionID.DLC4_AreYouFromTheseParts, "Unknown mission 195" },
			{ MissionID.DLC4_FightForYourRightToPartE, "Unknown mission 196" },
			{ MissionID.DLC4_PartsIsParts, "Unknown mission 197" },
			{ MissionID.DLC4_WeAllHaveOurPartToPlay, "Unknown mission 198" },
			{ MissionID.DLC4_APartOfSomethingLargerThanYourself, "Unknown mission 199" },
			{ MissionID.DLC4_NewContact, "Unknown mission 200" },
			{ MissionID.DLC4_LikeShootinRakkInABarrel, "Unknown mission 201" },
			{ MissionID.DLC4_SpaVsSpa, "Unknown mission 202" },
			{ MissionID.DLC4_OneUpmanPipp, "Unknown mission 203" },
			{ MissionID.DLC4_BurninRubber, "Unknown mission 204" },
			{ MissionID.DLC4_OperationTrapClaptrapTrapPhaseOne, "Unknown mission 205" },
			{ MissionID.DLC4_ItsATrapClap, "Unknown mission 206" },
			{ MissionID.DLC4_FingerLickinBad, "Unknown mission 207" },
			{ MissionID.DLC4_OperationTrapClaptrapTrapPhaseTwoIndustrialRevolution, "Unknown mission 208" },
			{ MissionID.DLC4_TakingStock, "Unknown mission 209" },
			{ MissionID.DLC4_OperationTrapClaptrapTrapPhaseThreeTripwired, "Unknown mission 210" },
			{ MissionID.DLC4_NotMyFault, "Unknown mission 211" },
			{ MissionID.DLC4_OldSpicy, "Unknown mission 212" },
			{ MissionID.DLC4_ElevenRakkAndSpices, "Unknown mission 213" },
			{ MissionID.DLC4_OperationTrapClaptrapTrapPhaseFourReboot, "Unknown mission 214" },
			{ MissionID.DLC4_HelpingIsItsOwnRewardWaitNoItIsnt, "Unknown mission 215" },
		};
	}
}
